# Generated by Django 5.0.6 on 2024-09-17 07:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_category_advertisements_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisements',
            options={'verbose_name': 'Advertisement', 'verbose_name_plural': 'Advertisements'},
        ),
        migrations.AddField(
            model_name='advertisements',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisements',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
