# Generated by Django 5.0.6 on 2024-09-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_postimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postimage',
            options={'verbose_name': 'Post Image', 'verbose_name_plural': 'Post Images'},
        ),
        migrations.AddField(
            model_name='advertisements',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/advertisements/images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='advertisements',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/advertisements/images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='advertisements',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/advertisements/images/%Y/%m/%d/'),
        ),
    ]
