# Generated by Django 5.0.6 on 2024-09-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_alter_postimage_options_advertisements_image_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('like_count', models.IntegerField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='uploads/platform/images/%Y/%m/%d/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='uploads/platform/images/%Y/%m/%d/')),
            ],
        ),
    ]
