# Generated by Django 5.0.6 on 2024-09-18 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_socialmedia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialmedia',
            options={'verbose_name': 'Social Media', 'verbose_name_plural': 'Social Medias'},
        ),
    ]
