# Generated by Django 5.0.6 on 2024-09-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_alter_socialmedia_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedia',
            old_name='image1',
            new_name='image_1',
        ),
        migrations.RenameField(
            model_name='socialmedia',
            old_name='like_count',
            new_name='likes',
        ),
        migrations.RemoveField(
            model_name='socialmedia',
            name='image2',
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/platform/images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='socialmedia',
            name='link',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
