# Generated by Django 5.0.6 on 2024-09-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_rename_image1_socialmedia_image_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedia',
            old_name='image_1',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='socialmedia',
            old_name='image_2',
            new_name='image2',
        ),
    ]
